repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: flake8
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.2
    hooks:
      - id: autopep8
